### ISSUE TITLE
Ask about copy cookie.

### ISSUE THREAD

**Issue by PogusTheWhisper** [EverStarck/anon-ig-stories-viewer#1]
![image](https://github.com/EverStarck/anon-ig-stories-viewer/assets/50095486/b8b4a9bc-ad8d-4ec9-9fe2-8692d55655b0)

**Comment by EverStarck** [comment]
Search for `Request Headers` on the network tab and copy the `Cookie` value

![imagen](https://github.com/EverStarck/anon-ig-stories-viewer/assets/51029456/c45aaf56-7883-4395-a498-1b80742a6d14)
